name: Update Repo
on:
  schedule:
    - cron: '0 16-22 * * *'
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: update data
        run: |
          echo ::set-output name=date::$(python scripts/update.py)
        id: run_script
      - name: update readme
        if: steps.run_script.outputs.date != 'Nop'
        run: |
          bash scripts/readme.sh
      - name: commit
        env:
          DATE: ${{ steps.run_script.outputs.date }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.run_script.outputs.date != 'Nop'
        run: |
          git config --global user.email "covid19-bot@example.com"
          git config --global user.name "covid19-bot"
          git add -A
          git status
          git commit -m "[ci] $DATE"
          git push -q "https://$GH_TOKEN@github.com/mauforonda/covid19-bo-municipios.git" master
